# Load Color Scheme
import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: xterm-256color

font:
  size: 12
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular

window:
  padding:
    x: 12
    y: 8
  decorations: none
  opacity: 1
